//  ABMNZN SDK 2025-10-08-7cwzfr4h
if (window.amazon == null || window.amazon.Login == null) {
(function() {
var l,m,n,q,t,w,x,y,A;function aa(a,b){if(null===a||void 0===a)a={};for(var c=1;c<arguments.length;c++){var e=arguments[c];if(null!==e&&void 0!==e)for(var d in e)a[d]=e[d]}return a}function B(a,b){var c=C.apply(void 0,arguments);ba("error",c);throw Error(c);}function C(a,b){var c=arguments,e=1;return a.replace(/%((%)|[sid])/g,function(a){if(a[2])return a[2];a=c[e++];"object"==typeof a&&window.JSON&&window.JSON.stringify&&(a=window.JSON.stringify(a));return a})}
function ba(a,b){window.console&&window.console.log&&("function"==typeof b&&(b=b()),b=C("[Amazon.%s] %s",a,b),window.console.log(b))}function ca(a){a&&"delegate"===a||B("expected %s value to be %s but was %s","options.response_type","delegate",a)}function F(a,b,c){null==b&&B("missing %s",a);typeof b!=c&&B("expected %s to be a %s",a,c)}
function da(a){var b=document.getElementById(a);b||(b=document.createElement("div"),b.setAttribute("id",a),b.setAttribute("width",0),b.setAttribute("height",0),b.setAttribute("style","position: absolute; left: -1000px; top: -1000px"),b.style.setAttribute&&b.style.setAttribute("cssText","position: absolute; left: -1000px; top: -1000px"),a=document.getElementById("amazon-root"),a||(a=document.createElement("div"),a.setAttribute("id","amazon-root"),document.body.appendChild(a)),a.appendChild(b));return b}
function ja(){var a=da("amazon-client-credentials-root"),b=ka(16),c=document.createElement("iframe");c.setAttribute("name",b);a.appendChild(c);0==document.getElementsByName(b).length&&(a.removeChild(c),c=document.createElement('<iframe name="'+b+'"/>'),a.appendChild(c));c.setAttribute("id",b);return b}function G(){this.a=[]}G.prototype.wait=function(a,b){this.a.push({za:a,persist:!!b})};
G.prototype.b=function(a){var b=this.a;this.a=[];for(var c=0;c<b.length;c++)b[c].persist&&this.a.push(b[c]);for(c=0;c<b.length;c++)b[c].za.apply(void 0,arguments)};
var H=function(){function a(){switch(f){case "t":return d("t"),d("r"),d("u"),d("e"),!0;case "f":return d("f"),d("a"),d("l"),d("s"),d("e"),!1;case "n":return d("n"),d("u"),d("l"),d("l"),null}g("Unexpected '"+f+"'")}function b(){for(;f&&" ">=f;)d()}function c(){var a,b="",c;if('"'===f)for(;d();){if('"'===f)return d(),b;if("\\"===f)if(d(),"u"===f){for(a=c=0;4>a;a+=1){var e=parseInt(d(),16);if(!isFinite(e))break;c=16*c+e}b+=String.fromCharCode(c)}else if("string"===typeof h[f])b+=h[f];else break;else b+=
f}g("Bad string")}function e(){var a="";"-"===f&&(a="-",d("-"));for(;"0"<=f&&"9">=f;)a+=f,d();if("."===f)for(a+=".";d()&&"0"<=f&&"9">=f;)a+=f;if("e"===f||"E"===f){a+=f;d();if("-"===f||"+"===f)a+=f,d();for(;"0"<=f&&"9">=f;)a+=f,d()}a=+a;if(isFinite(a))return a;g("Bad number")}function d(a){a&&a!==f&&g("Expected '"+a+"' instead of '"+f+"'");f=p.charAt(k);k+=1;return f}function g(a){throw{name:"SyntaxError",message:a,La:k,text:p};}var k,f,h={'"':'"',"\\":"\\","/":"/",u:"\b",H:"\f",n:"\n",r:"\r",t:"\t"},
p;var u=function(){b();switch(f){case "{":a:{var k={};if("{"===f){d("{");b();if("}"===f){d("}");var h=k;break a}for(;f;){h=c();b();d(":");Object.hasOwnProperty.call(k,h)&&g('Duplicate key "'+h+'"');k[h]=u();b();if("}"===f){d("}");h=k;break a}d(",");b()}}g("Bad object");h=void 0}return h;case "[":a:{h=[];if("["===f){d("[");b();if("]"===f){d("]");break a}for(;f;){h.push(u());b();if("]"===f){d("]");break a}d(",");b()}}g("Bad array");h=void 0}return h;case '"':return c();case "-":return e();default:return"0"<=
f&&"9">=f?e():a()}};return function(a,c){p=a;k=0;f=" ";a=u();b();f&&g("Syntax error");return"function"===typeof c?function r(a,b){var d,e=a[b];if(e&&"object"===typeof e)for(d in e)if(Object.prototype.hasOwnProperty.call(e,d)){var f=r(e,d);void 0!==f?e[d]=f:delete e[d]}return c.call(a,b,e)}({"":a},""):a}}(),J=function(){function a(a){return 10>a?"0"+a:a}function b(a){e.lastIndex=0;return e.test(a)?'"'+a.replace(e,function(a){var b=k[a];return"string"===typeof b?b:"\\u"+("0000"+a.charCodeAt(0).toString(16)).slice(-4)})+
'"':'"'+a+'"'}function c(a,e){var k=d,h=e[a];h&&"object"===typeof h&&"function"===typeof h.toJSON&&(h=h.toJSON(a));"function"===typeof f&&(h=f.call(e,a,h));switch(typeof h){case "string":return b(h);case "number":return isFinite(h)?String(h):"null";case "boolean":case "null":return String(h);case "object":if(!h)return"null";d+=g;var p=[];if("[object Array]"===Object.prototype.toString.apply(h)){var z=h.length;for(a=0;a<z;a+=1)p[a]=c(a,h)||"null";e=0===p.length?"[]":d?"[\n"+d+p.join(",\n"+d)+"\n"+
k+"]":"["+p.join(",")+"]";d=k;return e}if(f&&"object"===typeof f)for(z=f.length,a=0;a<z;a+=1){if("string"===typeof f[a]){var E=f[a];(e=c(E,h))&&p.push(b(E)+(d?": ":":")+e)}}else for(E in h)Object.prototype.hasOwnProperty.call(h,E)&&(e=c(E,h))&&p.push(b(E)+(d?": ":":")+e);e=0===p.length?"{}":d?"{\n"+d+p.join(",\n"+d)+"\n"+k+"}":"{"+p.join(",")+"}";d=k;return e}}"function"!==typeof Date.prototype.toJSON&&(Date.prototype.toJSON=function(){return isFinite(this.valueOf())?this.getUTCFullYear()+"-"+a(this.getUTCMonth()+
1)+"-"+a(this.getUTCDate())+"T"+a(this.getUTCHours())+":"+a(this.getUTCMinutes())+":"+a(this.getUTCSeconds())+"Z":null},String.prototype.toJSON=Number.prototype.toJSON=Boolean.prototype.toJSON=function(){return this.valueOf()});var e=/[\\"\x00-\x1f\x7f-\x9f\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,d,g,k={"\b":"\\b","\t":"\\t","\n":"\\n","\f":"\\f","\r":"\\r",'"':'\\"',"\\":"\\\\"},f;return function(a,b,e){var k;g=d="";if("number"===typeof e)for(k=
0;k<e;k+=1)g+=" ";else"string"===typeof e&&(g=e);if((f=b)&&"function"!==typeof b&&("object"!==typeof b||"number"!==typeof b.length))throw Error("JSON.stringify");return c("",{"":a})}}();function K(a){var b="",c;for(c in a)b&&(b+="&"),b+=encodeURIComponent(c)+"="+encodeURIComponent(a[c]+"");return b}
(function(){function a(a,c){for(var b=0;b<c.length;b++){var d=c[b];""==d||a.b.hasOwnProperty(d)||(a.a.push(d),a.b[d]=1)}}m=function(b){this.a=[];b="string"==typeof b?b.split(/\s+/):b;this.b={};a(this,b)};m.prototype.contains=function(a){for(var b=0;b<a.a.length;b++)if(!this.b.hasOwnProperty(a.a[b]))return!1;return!0};m.prototype.add=function(b){a(this,b.a)};m.prototype.i=function(a){for(var b=0;b<this.a.length;b++)a(this.a[b])};m.prototype.toString=function(){return this.a.join(" ")}})();
(function(){n={};var a=null;n.c=function(){return a};n.J=function(b){F("domain",b,"string");b=b.replace(/^\s+|\s+$/g,"");var c="."+window.location.hostname;"."!=b.charAt(0)&&(b="."+b);c.indexOf(b)!=c.length-b.length&&B("Site domain must contain the current page's domain");a=b};n.R=function(){};n.R.prototype.getItem=function(){};n.R.setItem=function(){};n.R.removeItem=function(){}})();
(function(){function a(){}a.prototype.getItem=function(a){a=(new RegExp("(?:^|;)\\s*"+escape(a).replace(/[\-\.\+\*]/g,"\\$&")+"\\s*\\=\\s*([^;]*)(?:;|$)")).exec(document.cookie);return null==a?null:unescape(a[1])};a.prototype.setItem=function(a,c,e){var b=null==e?"Fri, 31 Dec 9999 23:59:59 GMT":(new Date((new Date).getTime()+1E3*e)).toGMTString();var g=n.c();g=null==g?"":";Domain="+g;var k=la(L(window.location.href))?"":";Secure";document.cookie=a+"="+escape(c)+("session"==e?"":";Expires="+b)+g+";Path=/"+
k};a.prototype.removeItem=function(a){n.h.setItem(a,"null",0)};n.h=new a})();(function(){function a(a){this.a=a}a.prototype.getItem=function(a){return this.a.getItem(a)};a.prototype.setItem=function(a,c,e){this.a.setItem(a,c,e)};a.prototype.removeItem=function(a){n.h.removeItem(a)};n.C=new a(n.h)})();
q={Aa:function(a){var b=n.h.getItem("amazon_Login_auth_code_scope_cache");if(b)return b=H(b),b[a]},va:function(a,b){var c={};c[a]=b;n.C.setItem("amazon_Login_auth_code_scope_cache",J(c),240)},wa:function(a,b,c){"bearer"==a.token_type&&(a=J({access_token:a.access_token,max_age:c,expiration_date:(new Date).getTime()+1E3*c,client_id:t.fa(),scope:b}),n.C.setItem("amazon_Login_state_cache",a,"session"))},U:function(){var a=n.C.getItem("amazon_Login_state_cache");return null!=a&&(a=H(a),null!=a&&a.expiration_date>
(new Date).getTime())?(a.scope=new m(a.scope),a):null},S:function(){n.C.removeItem("amazon_Login_state_cache")}};function M(){return window.XMLHttpRequest&&"withCredentials"in new window.XMLHttpRequest||"undefined"!==typeof window.XDomainRequest?!0:!1}
function P(a,b,c,e,d,g){this.j=new Q(a,b,c);"string"==typeof e&&e||B("missing or invalid path: %s",e);this.i=e;"object"==typeof d&&(d=K(d));d&&"string"!=typeof d&&B("invalid query: %s",d);this.b=d||"";"object"==typeof g&&(g=K(g));g&&"string"!=typeof g&&B("invalid fragment: %s",g);this.a=g||""}
function L(a){var b=function(){var b=document.createElement("div");b.innerHTML="<a></a>";b.firstChild.href=a;b.innerHTML=b.innerHTML;return b.firstChild}();""==b.host&&(b.href=b.href);return new P(b.protocol,b.hostname,function(){var a=b.port;a&&"0"!=a||(a=null);return a}(),function(){var a=b.pathname;a?"/"!=a[0]&&(a="/"+a):a="/";return a}(),b.search.substring(1),b.href.split("#")[1]||"")}l=P.prototype;l.scheme=function(){return this.j.scheme()};l.host=function(){return this.j.host()};l.port=function(){return this.j.port()};
l.path=function(){return this.i};l.query=function(){return this.b};l.v=function(){return this.a};function la(a){var b="http"==a.j.scheme();a=a.j.host();return b&&("localhost"==a||"127.0.0.1"==a)}l.toString=function(){var a=this.j.toString();a+=this.i;a+=this.b?"?"+this.b:"";return a+=this.a?"#"+this.a:""};
function na(a,b){return new P(void 0!==b.scheme?b.scheme:a.scheme(),void 0!==b.host?b.host:a.host(),void 0!==b.port?b.port:a.port(),void 0!==b.path?b.path:a.path(),void 0!==b.query?b.query:a.query(),void 0!==b.v?b.v:a.v())}
function Q(a,b,c){var e;"string"==typeof a&&(e=a.match(/^(https?)(:(\/\/)?)?$/i))||B("missing or invalid scheme: %s",a);this.a="http"==e[1]?"http":"https";if(a="string"==typeof b&&b)"string"==typeof b&&b||B("missing or invalid input: %s",b),a=0!=b.replace(/^\s+|\s+$/g,"").length;a||B("missing or invalid host: %s",b);this.i=b;c&&((c+"").match(/^\d+$/)||B("invalid port: %s",c),80==c&&"http"==this.a||443==c&&"https"==this.a)&&(c=null);this.b=c?c+"":null}Q.prototype.scheme=function(){return this.a};
Q.prototype.host=function(){return this.i};Q.prototype.port=function(){return this.b};Q.prototype.toString=function(){var a=this.a+"://";a+=this.i;return a+=this.b?":"+this.b:""};function R(a,b,c,e){return new P(a.a,a.i,a.b,b,c,e)}function ka(a){for(var b="",c=0;c<a;c++)b+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789".charAt(Math.floor(62*Math.random()));return b}var S={},T=null;
function oa(a,b){var c=pa(a);var e=a.host().replace(/[^a-z0-9]/ig,"_");a.port()&&(e+="_"+a.port());e=C("amazon-proxy-%s-%s",a.scheme(),e);var d=document.getElementById(e);d||(d=document.createElement("iframe"),d.setAttribute("id",e),d.setAttribute("name",e),d.setAttribute("src",qa(a,c).toString()),da("amazon-proxy-root").appendChild(d));c=ka(16);S[c]||(S[c]=new G);S[c].wait(b,!1);b={uri:ra().toString(),proxy:e,topic:c,version:"3"};return R(a,"/sdk/2025-10-08-7cwzfr4h/topic.html",b,"")}
function pa(a){T||(T=ua(),T.ja(a,function(a,c){(a=S[a])&&a.b(c)}));return T}function ra(){return na(L(window.location.href),{query:"",v:""})}function qa(a,b){b={uri:ra().toString(),tr:b.name()};return R(a,"/ap/oa/proxy.html",{version:"3",build:"2025-10-08-7cwzfr4h"},b)}var xa=/^ABMNZNXDC;([\w\d_\-]+);(.*)$/;
function ya(a){if("string"===typeof a){var b=a.match(xa);if(b){a={};a.id=b[1];var c={};b=b[2].split("&");for(var e=0;e<b.length;e++){var d=b[e].split("=");2==d.length&&(c[d[0]]=decodeURIComponent(d[1].replace(/\+/g," ")))}a.data=c;return a}}return null}function ua(){var a=window.postMessage?"pm":"fr";window.__toucanForceTransport&&(a=window.__toucanForceTransport);if("pm"==a)a=new U;else if("fr"==a)a=new V;else throw B("unknown transport: %s",a),Error();return a}function U(){this.a=void 0}
U.prototype.name=function(){return"pm"};function Ba(a){if(void 0===a.a){var b=a.a=new G;a=function(a){var c;(c=ya(a.data))&&b.b(a.origin,c.id,c.data)};window.addEventListener?window.addEventListener("message",a,!1):window.attachEvent?window.attachEvent("onmessage",a):B("cannot attach message event")}}U.prototype.ja=function(a,b){Ba(this);var c=a.toString();this.a.wait(function(a,d,g){var e=L(window.location.href).j.toString();a!=c&&a!=e||b(d,g)},!0)};
U.prototype.send=function(a,b,c){var e=a.j,d=H(J(c));setTimeout(function(){window.parent.postMessage(C("%s;%s;%s","ABMNZNXDC",b,K(d)),e.toString())},1)};function V(){}V.prototype.name=function(){return"fr"};V.prototype.ja=function(a,b){window.__toucanInvokeFragment=function(a,e){b(a,e)}};
V.prototype.send=function(a,b,c){var e=a.query();(e=e||"")&&(e+="&");e=e+"ABMNZNXDC"+("="+ka(8));a=na(a,{query:e,v:C("%s;%s;%s","ABMNZNXDC",b,K(c))});b=document.createElement("iframe");b.setAttribute("src",a.toString());document.body.appendChild(b)};var Ca=window.location.href.split("#")[1]||"";if(Ca){var Da=ya(Ca);Da&&(document.documentElement.style.display="none","function"==typeof window.parent.parent.__toucanInvokeFragment&&window.parent.parent.__toucanInvokeFragment(Da.id,Da.data))}y={};A={};
(function(){function a(){this.code="AU"}a.prototype.c=function(){return"https://lwa.amazon.com.au"};a.prototype.a=function(){return"https://api.amazon.com.au"};a.prototype.f=function(){return this.code};A["com.au"]=new a;A.au=new a})();(function(){function a(){this.code="BR"}a.prototype.c=function(){return"https://lwa.amazon.com.br"};a.prototype.a=function(){return"https://api.amazon.com.br"};a.prototype.f=function(){return this.code};A["com.br"]=new a;A.br=new a})();
(function(){function a(){this.code="CA"}a.prototype.c=function(){return"https://lwa.amazon.ca"};a.prototype.a=function(){return"https://api.amazon.ca"};a.prototype.f=function(){return this.code};A.ca=new a})();(function(){function a(){this.code="FR"}a.prototype.c=function(){return"https://lwa.amazon.fr"};a.prototype.a=function(){return"https://api.amazon.fr"};a.prototype.f=function(){return this.code};A.fr=new a})();
(function(){function a(){this.code="DE"}a.prototype.c=function(){return"https://lwa.amazon.de"};a.prototype.a=function(){return"https://api.amazon.de"};a.prototype.f=function(){return this.code};A.de=new a})();(function(){function a(){this.code="IN"}a.prototype.c=function(){return"https://lwa.amazon.in"};a.prototype.a=function(){return"https://api.amazon.in"};a.prototype.f=function(){return this.code};A["in"]=new a})();
(function(){function a(){this.code="IT"}a.prototype.c=function(){return"https://lwa.amazon.it"};a.prototype.a=function(){return"https://api.amazon.it"};a.prototype.f=function(){return this.code};A.it=new a})();(function(){function a(){this.code="JP"}a.prototype.c=function(){return"https://lwa.amazon.co.jp"};a.prototype.a=function(){return"https://api.amazon.co.jp"};a.prototype.f=function(){return this.code};A["co.jp"]=new a;A.jp=new a})();
(function(){function a(){this.code="MX"}a.prototype.c=function(){return"https://lwa.amazon.com.mx"};a.prototype.a=function(){return"https://api.amazon.com.mx"};a.prototype.f=function(){return this.code};A["com.mx"]=new a;A.mx=new a})();(function(){function a(){this.code="NL"}a.prototype.c=function(){return"https://lwa.amazon.nl"};a.prototype.a=function(){return"https://api.amazon.nl"};a.prototype.f=function(){return this.code};A.nl=new a})();
(function(){function a(){this.code="ES"}a.prototype.c=function(){return"https://lwa.amazon.es"};a.prototype.a=function(){return"https://api.amazon.es"};a.prototype.f=function(){return this.code};A.es=new a})();(function(){function a(){this.code="UK"}a.prototype.c=function(){return"https://lwa.amazon.co.uk"};a.prototype.a=function(){return"https://api.amazon.co.uk"};a.prototype.f=function(){return this.code};A["co.uk"]=new a;A.uk=new a})();
(function(){function a(){this.code="US"}a.prototype.c=function(){return"https://lwa.amazon.com"};a.prototype.a=function(){return"https://api.amazon.com"};a.prototype.f=function(){return this.code};A.com=new a;A.us=new a})();(function(){function a(){this.code="APAC"}a.prototype.c=function(){return"https://apac.account.amazon.com"};a.prototype.a=function(){return"https://api.amazon.co.jp"};a.prototype.f=function(){return this.code};y.AsiaPacific=new a})();
(function(){function a(){this.code="CN"}a.prototype.c=function(){return"https://www.amazon.cn"};a.prototype.a=function(){return"https://api.amazon.cn"};a.prototype.f=function(){return this.code};y.China=new a;A.cn=new a})();(function(){function a(){this.code="EU"}a.prototype.c=function(){return"https://eu.account.amazon.com"};a.prototype.a=function(){return"https://api.amazon.co.uk"};a.prototype.f=function(){return this.code};y.Europe=new a})();
(function(){function a(){this.code="NA"}a.prototype.c=function(){return"https://na.account.amazon.com"};a.prototype.a=function(){return"https://api.amazon.com"};a.prototype.f=function(){return this.code};y.NorthAmerica=new a})();
(function(){function a(a){var b=a.match(Aa);b||B("invalid domain: %s",a);var c=b[2]?b[2].toLowerCase():"https";"https"!=c&&B("invalid domain: %s; scheme must be https",a);a=b[3];a.match(/^amazon\.[a-z\.]+$/)&&(a="www."+a);return new Q(c,a,b[5])}function b(a){a&&(t.J(a.c()),t.ma(a.a()))}function c(a){a=aa({interactive:void 0,popup:!0,response_type:"token",response_mode:void 0,delegated_requests:void 0,direct_post_uri:void 0,state:void 0,scope:void 0,scope_data:void 0,optional_scope:void 0,"com.amazon.oauth2.options":void 0,
workflow_data:void 0,pkce:!1,code_challenge:void 0,code_challenge_method:"S256"},a||{});F("options.response_type",a.response_type,"string");a.response_mode&&F("options.response_mode",a.response_mode,"string");a.direct_post_uri&&F("options.direct_post_uri",a.direct_post_uri,"string");a[r.sa]&&a[r.P]===r.$&&a.interactive!==v.NEVER&&!0!==a[r.w]&&M()&&(a[r.w]=!0,a[r.O]=!0);if(!0===a[r.w]||a[r.m])a[r.P]="code";var b=a.delegated_requests;if(b){ca(a.response_type);a.scope&&B("options.scope is not supported for delegated authorization");
a.scope_data&&B("options.scope_data is not supported for delegated authorization");a.optional_scope&&B("options.optional_scope is not supported for delegated authorization");a.interactive?a.interactive!=v.ALWAYS&&B("options.interactive should be '"+v.ALWAYS+"' for delegated authorization"):a.interactive=v.ALWAYS;for(var c={},ea=0;ea<b.length;ea++){var f=b[ea],h=e(a,f);c[f.request_id]=h}a.delegated_requests=c}else if(d(a,"missing options.scope"),g(a),k(a),a.interactive?a.interactive!=v.M&&a.interactive!=
v.ALWAYS&&a.interactive!=v.NEVER&&B("expected options.interactive to be one of '"+v.M+"', '"+v.ALWAYS+"', or '"+v.NEVER+"'"):a.interactive=v.M,a.optional_scope){a.optional_scope.constructor!==Array&&"string"!=typeof a.optional_scope&&B("expected options.optional_scope to be a string or array");a.interactive!=v.NEVER&&B("options.optional_scope is only supported for options.interactive = never");b=new m(a.optional_scope);a.scope.add(b);var p={id_token:{}};b.i(function(a){p.id_token[a]={essential:!1}});
a.optional_scope=J(p)}return a}function e(a,b){b.response_mode&&B("response_mode is not supported in delegated requests");b.direct_post_uri&&B("direct_post_uri is not supported in delegated requests");"popup"in b&&B("popup is not supported in delegated requests");b.interactive&&B("interactive mode is not supported in delegated requests");b.optional_scope&&B("optional_scope is not supported in delegated requests");b.delegated_requests&&B("delegated_requests is not supported in delegated requests");
null==b.response_type&&(b.response_type="token");d(b,"missing 'scope' in delegated request");b.scope=b.scope.toString();g(b);k(a);F("request_id",b.request_id,"string");b.client_id&&!b.client_id.match(ma)&&B("invalid client_id format: %s",b.client_id);a={};for(var c in b)"request_id"!=c&&(a[c]=b[c]);return a}function d(a,b){a.scope||B(b);a.scope.constructor!==Array&&"string"!=typeof a.scope&&B("expected scope to be a string or array");a.scope=new m(a.scope)}function g(a){a.scope_data&&(a.scope_data=
J(a.scope_data))}function k(a){if(a.workflow_data){var b={};b.workflow_data=a.workflow_data;a["com.amazon.oauth2.options"]=J(b)}}function f(a){var b=(void 0!==window.screenX?window.screenX:window.screenLeft)+Math.floor(((void 0!==window.outerWidth?window.outerWidth:document.documentElement.clientWidth)-800)/2),c=(void 0!==window.screenY?window.screenY:window.screenTop)+Math.floor(((void 0!==window.outerHeight?window.outerHeight:document.documentElement.clientHeight)-540)/2);b=C("left=%s,top=%s,width=%s,height=%s,scrollbars=1",
0>b?0:b,0>c?0:c,800,540);N=window.open(a.toString(),"amazonloginpopup",b)}function h(){null!=N&&("function"==typeof N.close&&N.close(),N=null)}function p(a,b,c){var d={client_id:W,redirect_uri:b,response_type:a.response_type,language:sa,ui_locales:ta};a["com.amazon.oauth2.options"]&&(d["com.amazon.oauth2.options"]=a["com.amazon.oauth2.options"]);a.response_mode&&(d.response_mode=a.response_mode);a.scope&&(d.scope=a.scope.toString());a.direct_post_uri&&(d.direct_post_uri=a.direct_post_uri);a.scope_data&&
(d.scope_data=a.scope_data);fa&&(d.sandbox=!0);a.state&&(d.state=a.state);c&&(d.exac=c);a.delegated_requests&&(d.delegated_requests=J(a.delegated_requests));if((c=d.scope)&&-1!==c.indexOf("payments:widget")){c=d.sandbox;var e=d.scope_data;try{var f=e&&""!==e?JSON.parse(e):{}}catch(Ha){f={}}Ea(f,c,b);-1===JSON.stringify(f).indexOf("payments:widget")&&(f={},Ea(f,c,b));b=JSON.stringify(f);d.scope_data=b}a[r.m]&&(d[r.m]=a[r.m],d[r.N]=a[r.N]);!0!==a[r.w]||a[r.m]||(d[r.m]=w.Ba(d.client_id,d.redirect_uri),
d[r.N]="S256");a=R(O,"/ap/oa",d);if(8196<a.toString().length)throw console.error("URI has exceeded url length limit of 8196. Current Length of the URI: "+a.toString().length),400;return a}function u(a,b,c){X=!1;b.access_token?t.ba(b,b.scope):c&&n.h.removeItem(t.o);b.code&&!0===a.a[r.w]&&q.va(b.code,b.scope);a.oa(b);a=ha;ha=[];for(b=0;b<a.length;b++)z(a[b])}function I(a,b,c,d){var e=K(a);!c&&d?(a=L(b),a=na(a,{v:e})):(b+=-1==b.indexOf("?")?"?":"&",b+=e,a=L(b));e=L(window.location.href);"https"==a.scheme()||
la(a)||B("attempted redirect to %s but scheme is not HTTPS",b);a.host()!=e.host()&&B("attempted redirect to %s but it does not match current host %s",a.host(),e.host());!c&&d?window.top.location.href=a.toString():(h(),window.location.href=b)}function D(a){var b=this;this.a=a;this.i=null;this.X=[];this.W=null;this.b={status:null,onComplete:function(a){"string"!=typeof a&&"function"!=typeof a&&B("onComplete expects handler parameter to be a function or a string");var c=b.b.status==Y.Z;"string"==typeof a?
c?I(b.W,a,b.a.popup,"token"==b.a.response_type):b.i=a:"function"==typeof a&&(c?setTimeout(function(){a(b.b)},0):b.X.push(a));return b.b}}}function z(a){var b=a.a,c=null;if(b.delegated_requests)E(a,null);else{if(b.interactive==v.ALWAYS)q.S();else{var d=null;t.na()&&(d=n.h.getItem(t.o));if(c=q.U())"token"==b.response_type&&b.scope.add(c.scope),d?d!=c.access_token&&(q.S(),c=null):d=c.access_token;if(c&&c.scope.contains(b.scope)&&(b[r.P]===r.$||!0===b[r.O])){var e={access_token:c.access_token,token_type:"bearer",
expires_in:Math.floor((c.expiration_date-(new Date).getTime())/1E3),scope:c.scope.toString()};null!=b.state&&(e.state=b.state)}else if(b.interactive==v.NEVER&&b.popup){if(X){ha.push(a);a.Y(Y.ta);return}if(d){za(a,d);return}e={error:"invalid_grant",error_description:"invalid grant"}}if(e){setTimeout(function(){a.oa(e)},0);return}}E(a,d)}}function E(a,b){var c=a.a;if(c.popup){X=!0;var d=oa(O,function(b){h();b.code&&!0===c[r.O]?w.la(b.code,function(c){!0===c.success&&(c.scope=b.scope);c.success=null;
u(a,c,!0)}):u(a,b,!0)});b=p(a.a,d,b);f(b,a)}else(d=a.i)||B("Missing redirectUrl for redirect flow"),window.top.location.href=p(c,L(d+""),b).toString()}function za(a,b){X=!0;var c=da("amazon-client-credentials-root"),d=ja(),e=document.createElement("form");c.appendChild(e);e.setAttribute("method","POST");e.setAttribute("target",d);var f=oa(O,function(b){c.removeChild(e);var f=document.getElementById(d);null!=f&&null!=f.parentNode&&f.parentNode.removeChild(f);null==b&&(b={error:"server_error",description:"Server error."});
u(a,b,!1)}),g=a.a;b={client_id:W,exac:b,grant_type:"client_credentials",redirect_uri:f,response_type:g.response_type,scope:g.scope};null!=g.state&&(b.state=g.state);null!=g.response_mode&&(b.response_mode=g.response_mode);null!=g.direct_post_uri&&(b.direct_post_uri=g.direct_post_uri);null!=g.scope_data&&(b.scope_data=g.scope_data);null!=g.optional_scope&&(b.claims=g.optional_scope);null!=g["com.amazon.oauth2.options"]&&(b["com.amazon.oauth2.options"]=g["com.amazon.oauth2.options"]);e.setAttribute("action",
R(O,"/ap/oa",b).toString());e.submit()}t={qa:{w:"pkce",N:"code_challenge_method",m:"code_challenge",P:"response_type",O:"convert_implicit_to_pkce",sa:"popup",$:"token"},o:"amazon_Login_accessToken"};var r=t.qa,ma=/^[\w\-\.]+$/,Aa=/^((http|https):\/\/)?([a-z0-9\-\.]+)(:(\d+))?\/?$/i,v={ALWAYS:"always",M:"auto",NEVER:"never"},N=null,X=!1,ha=[],Y={ta:"queued",pa:"in_progress",Z:"complete"},W=void 0;t.fa=function(){return W};t.Ea=function(a){a.match(ma)||B("invalid client ID: %s",a);W=a};var ia="na.account.amazon.com",
O=new Q("https",ia,null),va=new Q("https","api.amazon.com",null);t.c=function(){return ia};t.T=function(){return va};var fa=!1;t.Ia=function(a){"number"==typeof a&&(a=!!a);F("sandboxMode",a,"boolean");fa=a};t.Ta=function(){return fa};t.J=function(b){O=a(b);ia=b};t.ma=function(b){va=a(b)};t.Ha=function(a){"string"===typeof a?a===y.Europe.f()?b(y.Europe):a===y.AsiaPacific.f()?b(y.AsiaPacific):a===y.China.f()?b(y.China):b(y.NorthAmerica):b(a)};t.Da=function(a){b(a)};var sa="";t.Fa=function(a){sa=a};
var ta="";t.Ga=function(a){ta=a};var wa=!1;t.na=function(){return wa};t.Ja=function(a){null==a?B("missing useCookie"):"number"==typeof a?a=!!a:"boolean"!=typeof a&&B("expected useCookie to be a boolean");wa=a};t.ba=function(a,b){var c=parseInt(a.expires_in,10);c=60>=c?c:c-Math.min(Math.floor(.1*c),300);q.wa(a,b,c);t.na()?n.h.setItem(t.o,a.access_token,c):n.h.removeItem(t.o)};D.prototype.oa=function(a){this.W=a;aa(this.b,a);this.Y(Y.Z);for(a=0;a<this.X.length;a++)this.X[a](this.b);null!=this.i&&I(this.W,
this.i,this.a.popup,"token"==this.a.response_type)};D.prototype.Y=function(a){this.b.status=a};t.aa=function(a,b){2>arguments.length&&B("authorize expects two arguments (options, next)");a&&"object"!=typeof a&&B("authorize expects options parameter to be an object");null!=b&&"function"!=typeof b&&"string"!=typeof b&&B("authorize expects next parameter to be a function or a string");a=c(a);var d=new D(a),e=d.b;d.Y(Y.pa);if(null!=b)e.onComplete(b);a.popup||"string"==typeof b?z(d):B("next must be redirect URI if !options.popup");
return e}})();
(function(){function a(a,c){try{var b=H(a)}catch(d){b=null}b&&b.error?(a={success:!1},a.error=C("%s: %s",b.error,b.error_description||"An unknown error occurred"),c(a)):b&&b.user_id?(a={success:!0},a.profile={PrimaryEmail:b.email,CustomerId:b.user_id,Name:b.name},c(a)):(a={success:!1,error:"UnknownError: Incomprehensible response from profile endpoint"},c(a))}x={ka:function(b,c){if(null==c&&"function"==typeof b)c=b,t.aa({scope:"profile"},function(a){null==a.error?x.ka(a.access_token,c):c({success:!1,
error:a.error})});else if(F("accessToken",b,"string"),F("callback",c,"function"),M()){b=R(t.T(),"/user/profile",{access_token:b},"").toString();if(window.XDomainRequest){var e=new window.XDomainRequest;e.onload=function(){a(e.responseText,c)}}else{var d=!1;e=new window.XMLHttpRequest;e.onreadystatechange=function(){d||4!=e.readyState||(d=!0,a(e.responseText,c))}}e.open("GET",b,!0);e.send()}else c({success:!1,error:"UnsupportedOperation: Cannot retrieve profile in this browser"})}}})();
(function(){function a(a,b,c){try{var d=H(a);n.h.removeItem(w.D)}catch(h){d=null}a={};d&&d.Error?(a.success=!1,a.error=C("%s: %s",d.Error.Code||"UnknownError",d.Error.Message||"An unknown error occurred")):d&&d.access_token?(a.success=!0,a.access_token=d.access_token,a.token_type=d.token_type,a.expires_in=d.expires_in,(b=q.Aa(b))&&t.ba(d,b)):(a.success=!1,a.error="UnknownError: Incomprehensible response from token endpoint");c(a)}function b(a,b){a={grant_type:"authorization_code",client_id:a.client_id,
redirect_uri:decodeURIComponent(a.redirect_uri),code_verifier:a.code_verifier,code:b};return J(a)}function c(){var a=n.h.getItem(w.D);return a?H(a):null}function e(){var a=q.U();return a?{success:!0,access_token:a.access_token,token_type:"bearer",expires_in:Math.floor((a.expiration_date-(new Date).getTime())/1E3),scope:a.scope.toString()}:null}w={D:"amazon_Login_pkce_params",ra:240,Ba:function(a,b){var d,e=c();e&&(e.client_id!=a?n.h.removeItem(w.D):e.code_verifier&&(d=e.code_verifier));if(!d){d="";
for(e=128;0<e;--e)d+="0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ"[Math.floor(62*Math.random())];d=encodeURIComponent(d)}a={client_id:a,code_verifier:d,redirect_uri:encodeURIComponent(b)};n.h.setItem(w.D,J(a),w.ra);a=Z.hash.K.hash(d);return Z.l.ua.I(a)},la:function(d,g){if(null==d&&null==g)return e();F("code",d,"string");F("callback",g,"function");var k={};if(M()){var f=c();if(f){k=b(f,d);var h=!1;if(window.XDomainRequest){var p=new window.XDomainRequest;p.onload=function(){a(p.responseText,
d,g)}}else p=new window.XMLHttpRequest,p.onreadystatechange=function(){h||4!=p.readyState||(h=!0,a(p.responseText,d,g))};p.open("POST",t.T()+"/auth/O2/token",!0);"function"===typeof p.setRequestHeader&&p.setRequestHeader("Content-Type","application/json");p.send(k)}else k.success=!1,k.error="UnsupportedOperation: Cookie amazon_Login_pkce_params not found. Cannot retrieve token without cookie.",g(k)}else k.success=!1,k.error="UnsupportedOperation: Cannot retrieve token in this browser",g(k)}}})();
(function(){function a(a,d){M()||c("UnsupportedOperation: Cannot remotely logout in this browser",d);var e=R(t.T(),"/auth/relyingPartyLogout",null,null).toString(),k={};k.token=a;k.token_type="bearer";if(window.XDomainRequest){var f=new window.XDomainRequest;f.onload=function(){b(f.responseText,d)}}else{var h=!1;f=new window.XMLHttpRequest;f.onreadystatechange=function(){h||4!=f.readyState||(h=!0,b(f.responseText,d))}}f.open("POST",e,!0);f.send(J(k))}function b(a,b){try{var d=H(a).response}catch(f){d=
void 0}if(!d||d.error){a="UnknownError";var e="An unknown error ocurred";d&&d.error&&d.error.code&&d.error.message&&(a=d.error.code,e=d.error.message);e=C("%s: %s",a,e)}c(e,b)}function c(a,b){a&&ba("logout",a);b&&"function"==typeof b&&b()}t.Ca=function(){var b=n.h.getItem(t.o),c=q.U();b&&n.h.removeItem(t.o);!b&&c&&(b=c.access_token);q.S();b&&a(b,void 0)}})();window.amazon=window.amazon||{};window.amazon.Login=window.amazon.Login||{};window.amazon.Login.getClientId=function(){return t.fa()};
window.amazon.Login.setClientId=function(a){return t.Ea(a)};window.amazon.Login.setDomain=function(a){return t.J(a)};window.amazon.Login.setAPIDomain=function(a){return t.ma(a)};window.amazon.Login.setSandboxMode=function(a){return t.Ia(a)};window.amazon.Login.setSiteDomain=function(a){return n.J(a)};window.amazon.Login.Region=y;window.amazon.Login.setRegion=function(a){return t.Ha(a)};window.amazon.Login.amazonDomain=A;window.amazon.Login.setAmazonDomain=function(a){return t.Da(a)};
window.amazon.Login.setLanguage=function(a){return t.Fa(a)};window.amazon.Login.setLanguageHint=function(a){return t.Ga(a)};window.amazon.Login.setUseCookie=function(a){return t.Ja(a)};window.amazon.Login.authorize=function(a,b){return t.aa(a,b)};window.amazon.Login.logout=function(){return t.Ca()};window.amazon.Login.retrieveProfile=function(a,b){return x.ka(a,b)};window.amazon.Login.retrieveToken=function(a,b){return w.la(a,b)};if("function"==typeof window.onAmazonLoginReady)window.onAmazonLoginReady();
function Ea(a,b,c){a["payments:widget"]={redirectUrl:c.j.toString(),originUrl:window.location.origin,isSandbox:b?b:!1}};var Z={Pa:{},hash:{},Va:{},mode:{},Wa:{},l:{},da:{Qa:function(a){this.toString=function(){return"CORRUPT: "+this.message};this.message=a},ia:function(a){this.toString=function(){return"INVALID: "+this.message};this.message=a},Na:function(a){this.toString=function(){return"BUG: "+this.message};this.message=a},Xa:function(a){this.toString=function(){return"NOT READY: "+this.message};this.message=a}},g:{Ma:function(a,b,c){a=Z.g.ha(a.slice(b/32),32-(b&31)).slice(1);return void 0===c?a:Z.g.xa(a,c-b)},
Sa:function(a,b,c){var e=Math.floor(-b-c&31);return((b+c-1^b)&-32?a[b/32|0]<<32-e^a[b/32+1|0]>>>e:a[b/32|0]>>>e)&(1<<c)-1},concat:function(a,b){if(0===a.length||0===b.length)return a.concat(b);var c=a[a.length-1],e=Z.g.V(c);return 32===e?a.concat(b):Z.g.ha(b,e,c|0,a.slice(0,a.length-1))},A:function(a){var b=a.length;return 0===b?0:32*(b-1)+Z.g.V(a[b-1])},xa:function(a,b){if(32*a.length<b)return a;a=a.slice(0,Math.ceil(b/32));var c=a.length;b&=31;0<c&&b&&(a[c-1]=Z.g.B(b,a[c-1]&2147483648>>b-1,1));
return a},B:function(a,b,c){return 32===a?b:(c?b|0:b<<32-a)+1099511627776*a},V:function(a){return Math.round(a/1099511627776)||32},Ra:function(a,b){if(Z.g.A(a)!==Z.g.A(b))return!1;var c=0,e;for(e=0;e<a.length;e++)c|=a[e]^b[e];return 0===c},ha:function(a,b,c,e){var d;for(void 0===e&&(e=[]);32<=b;b-=32)e.push(c),c=0;if(0===b)return e.concat(a);for(d=0;d<a.length;d++)e.push(c|a[d]>>>b),c=a[d]<<32-b;d=a.length?a[a.length-1]:0;a=Z.g.V(d);e.push(Z.g.B(b+a&31,32<b+a?c:e.pop(),1));return e},Ua:function(a,
b){return[a[0]^b[0],a[1]^b[1],a[2]^b[2],a[3]^b[3]]},Oa:function(a){var b;for(b=0;b<a.length;++b){var c=a[b];a[b]=c>>>24|c>>>8&65280|(c&65280)<<8|c<<24}return a}}};Z.l.Ka={I:function(a){var b="",c=Z.g.A(a),e,d;for(e=0;e<c/8;e++)0===(e&3)&&(d=a[e/4]),b+=String.fromCharCode(d>>>8>>>8>>>8),d<<=8;return decodeURIComponent(escape(b))},L:function(a){a=unescape(encodeURIComponent(a));var b=[],c,e=0;for(c=0;c<a.length;c++)e=e<<8|a.charCodeAt(c),3===(c&3)&&(b.push(e),e=0);c&3&&b.push(Z.g.B(8*(c&3),e));return b}};
Z.l.F={ea:"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/",I:function(a,b,c){var e="",d=0,g=Z.l.F.ea,k=0,f=Z.g.A(a);c&&(g=g.substr(0,62)+"-_");for(c=0;6*e.length<f;)e+=g.charAt((k^a[c]>>>d)>>>26),6>d?(k=a[c]<<6-d,d+=26,c++):(k<<=6,d-=6);for(;e.length&3&&!b;)e+="=";return e},L:function(a,b){a=a.replace(/\s|=/g,"");var c=[],e=0,d=Z.l.F.ea,g=0;b&&(d=d.substr(0,62)+"-_");for(b=0;b<a.length;b++){var k=d.indexOf(a.charAt(b));if(0>k)throw new Z.da.ia("this isn't base64!");26<e?(e-=26,c.push(g^
k>>>e),g=k<<32-e):(e+=6,g^=k<<32-e)}e&56&&c.push(Z.g.B(e&56,g,1));return c}};Z.l.ua={I:function(a){return Z.l.F.I(a,1,1)},L:function(a){return Z.l.F.L(a,1)}};Z.hash.K=function(a){this.H[0]||Fa(this);a?(this.G=a.G.slice(0),this.u=a.u.slice(0),this.s=a.s):this.reset()};Z.hash.K.hash=function(a){a=(new Z.hash.K).update(a);var b,c=a.u,e=a.G;c=Z.g.concat(c,[Z.g.B(1,1)]);for(b=c.length+2;b&15;b++)c.push(0);c.push(Math.floor(a.s/4294967296));for(c.push(a.s|0);c.length;)Ga(a,c.splice(0,16));a.reset();return e};
Z.hash.K.prototype={reset:function(){this.G=this.ga.slice(0);this.u=[];this.s=0;return this},update:function(a){"string"===typeof a&&(a=Z.l.Ka.L(a));var b=this.u=Z.g.concat(this.u,a);var c=this.s;a=this.s=c+Z.g.A(a);if(9007199254740991<a)throw new Z.da.ia("Cannot hash more than 2^53 - 1 bits");if("undefined"!==typeof Uint32Array){var e=new Uint32Array(b),d=0;for(c=512+c-(512+c&511);c<=a;c+=512)Ga(this,e.subarray(16*d,16*(d+1))),d+=1;b.splice(0,16*d)}else for(c=512+c-(512+c&511);c<=a;c+=512)Ga(this,
b.splice(0,16));return this},ga:[],H:[]};
function Ga(a,b){var c,e,d=a.G,g=a.H,k=d[0],f=d[1],h=d[2],p=d[3],u=d[4],I=d[5],D=d[6],z=d[7];for(a=0;64>a;a++)16>a?c=b[a]:(c=b[a+1&15],e=b[a+14&15],c=b[a&15]=(c>>>7^c>>>18^c>>>3^c<<25^c<<14)+(e>>>17^e>>>19^e>>>10^e<<15^e<<13)+b[a&15]+b[a+9&15]|0),c=c+z+(u>>>6^u>>>11^u>>>25^u<<26^u<<21^u<<7)+(D^u&(I^D))+g[a],z=D,D=I,I=u,u=p+c|0,p=h,h=f,f=k,k=c+(f&h^p&(f^h))+(f>>>2^f>>>13^f>>>22^f<<30^f<<19^f<<10)|0;d[0]=d[0]+k|0;d[1]=d[1]+f|0;d[2]=d[2]+h|0;d[3]=d[3]+p|0;d[4]=d[4]+u|0;d[5]=d[5]+I|0;d[6]=d[6]+D|0;d[7]=
d[7]+z|0}function Fa(a){function b(a){return 4294967296*(a-Math.floor(a))|0}for(var c=0,e=2,d,g;64>c;e++){g=!0;for(d=2;d*d<=e;d++)if(0===e%d){g=!1;break}g&&(8>c&&(a.ga[c]=b(Math.pow(e,.5))),a.H[c]=b(Math.pow(e,1/3)),c++)}}"undefined"!==typeof module&&module.ya&&(module.ya=Z);"function"===typeof define&&define([],function(){return Z});

})();
}
